name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Access Api keys
      env:
        clientId: ${{ secrets.APOD_API_KEY }}
        path: app/src/main/res/values/apikeys.xml
      run: |
        echo "clientId: $clientId"
        echo $clientId | xargs sed -i "s|</resources>|<string name=\"CLIENT_ID\">$clientId</string>\n</resources>|g" $path
