name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set BASE_URL
        run: |
          # Secret'i bir değişken olarak kullanabilirsiniz
          BASE_URL=${{ secrets.BASE_URL }}
          echo "BASE_URL=$BASE_URL" > base_url.txt
          # Diğer işlemlerinizi burada gerçekleştirin

      - name: Upload BASE_URL
        uses: actions/upload-artifact@v2
        with:
          name: base_url
          path: base_url.txt
