name: My Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Access Api keys
        env:
          clientId: 'Snyk Demo'
          path: app/src/main/res/values/apikeys.xml
        run: |
          touch $path
          echo '<resources>' >> $path
          echo "<string name=\"CLIENT_ID\">$clientId</string>" >> $path
          echo '</resources>' >> $path

          
