name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access APOD_API_KEY
        env:
          APOD_API_KEY: ${{ secrets.APOD_API_KEY }}
        run: echo APOD_API_KEY="$APOD_API_KEY" > ./local.properties

