name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Access Api keys
        env:
          clientId: ${{ secrets.APOD_API_KEY }}
          path: app/src/main/res/values/apikeys.xml
        run: |
          echo '<resources>' >> $path
          echo "<string name=\"CLIENT_ID\">$clientId</string>" >> $path
          echo '</resources>' >> $path

          
