on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set BASE_URL
        run: |
          # Secret'i bir değişken olarak kullanabilirsiniz
          BASE_URL=${{ secrets.BASE_URL }}
          echo "BASE_URL=$BASE_URL" > base_url.txt
          # Diğer işlemlerinizi burada gerçekleştirin

      - name: Get and Use Run ID in URL
        id: get_and_use_run_id
        run: |
          # Get the run ID
          RUN_ID="${{ github.run_id }}"
          echo "RUN_ID=$RUN_ID"

          # Get the base URL
          val client = OkHttpClient()
          val request = Request.Builder()
              .url("https://api.github.com/repos/burakselcuk1/GithubSecret/actions/artifacts/runs/$RUN_ID/artifacts/base_url")
              .get()
              .build()

          try {
              val response = client.newCall(request).execute()
              if (response.isSuccessful) {
                  echo "BASE_URL=${response.body()?.string()}"
              } else {
                  echo "Network request failed."
              }
          } catch (e: IOException) {
              e.printStackTrace()
          }
