name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Access Api keys
        env:
          clientId: ${{ secrets.APOD_API_KEY }}
          path: app/src/main/res/values/secrets.xml
        run: |
          mkdir -p app/src/main/res/values
          echo "clientId: $clientId" 
          echo '<?xml version="1.0" encoding="utf-8"?>' > $path
          echo '<resources>' >> $path
          echo "<string name=\"CLIENT_ID\">$clientId</string>" >> $path
          echo '</resources>' >> $path
