name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Access Api keys
        env:
          clientId: ${{ secrets.APOD_API_KEY }}
          path: app/src/main/res/values/secrets.xml
        run: |
          touch $path
          echo '<resources>' >> $path
          echo '<string name="CLIENT_ID">YOUR_API_KEY</string>' >> $path
          echo '</resources>' >> $path
