on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set BASE_URL
        run: |
          # Secret'i bir değişken olarak kullanabilirsiniz
          BASE_URL=${{ secrets.BASE_URL }}
          echo "BASE_URL=$BASE_URL" > base_url.txt
          # Diğer işlemlerinizi burada gerçekleştirin

      - name: Get Run ID
        id: run_id
        run: |
          echo "::set-output name=run_id::${{ github.run_id }}"
        
      - name: Use Run ID in URL
        run: |
          RUN_ID="${{ steps.run_id.outputs.run_id }}"
          URL="https://api.github.com/repos/burakselcuk1/GithubSecret/actions/artifacts/runs/$RUN_ID/artifacts/base_url"
          # URL'i kullanarak isteği yapabilirsiniz
